timesheet/models.py
from datetime import datetime, date
from timesheet import db, login_manager
from flask_login import UserMixin

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(120), unique=True, nullable=False) #Blaise Cosico
    username = db.Column(db.String(20), unique=True, nullable=False) #C81440
    email = db.Column(db.String(120), unique=True, nullable=False)
    position = db.Column(db.String(120), nullable=False)
    password = db.Column(db.String(60), nullable=False)
    daily = db.relationship('Daily', backref='employee', lazy=True) #fix naming convention

    def __repr__(self):
        return f"User('{self.username}', '{self.position}')"
    
class Daily(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date_today = db.Column(db.DateTime, nullable=False, default=date.today) #default=datetime.utcnow
    time_in = db.Column(db.String(20), nullable=True) #SQLite DateTime type only accepts Python datetime and date objects as input.
    time_out = db.Column(db.String(20), nullable=True)
    user_id = db.Column(db.String, db.ForeignKey('user.username'), nullable=False)

    def __repr__(self):
        return f"Daily('{self.user_id}', '{self.date_today}')"  

timesheet/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_login import current_user
# from flaskblog.models import User

class LoginForm(FlaskForm):
    username = StringField('Username',
                        validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Login')

class RegistrationForm(FlaskForm):

    fname = StringField('First Name', validators=[DataRequired()])
    lname = StringField('Last Name', validators=[DataRequired()])
    username = StringField('IPI ID', validators=[DataRequired(), Length(min=6, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    position = StringField('Position', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',
                                      validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')

class AccountForm(FlaskForm):
    username = StringField('IPI ID', validators=[DataRequired(), Length(min=6, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Update')

    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('That email is taken. Please choose a different one.')

timesheet/__init__.py
from flask import Flask
from timesheet.config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager

db = SQLAlchemy()
login_manager = LoginManager()
bcrypt = Bcrypt()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)

    from timesheet.main.routes import main
    from timesheet.users.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)
    
    return app

timesheet/main/routes.py
import sys
from flask import Blueprint, render_template, request
from datetime import datetime, date, timedelta
from timesheet.models import Daily

main = Blueprint('main', __name__)

posts = [
    {
        'name': 'Blaise Cosico',
        'position': 'Developer',
        'time_in': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'time_out': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    },
    {
        'name': 'Corey Schafer',
        'position': 'Developer',
        'time_in': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
        'time_out': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
    }
]

@main.route('/')
@main.route('/home')
def home():
    # daily = Daily.query.all()
    daily = Daily.query.order_by(Daily.time_in.desc()) #.paginate(page=page, per_page=5)
    return render_template('homepage.html', title='Homepage', daily=daily)

@main.route('/posts')
def posts_():
    # print(f'datetime now: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}', file=sys.stderr)
    # print(f'date now: {date.today()}', file=sys.stderr)
    # print(f'time now: {datetime.now().strftime("%H:%M:%S")}', file=sys.stderr)
    return render_template('posts.html', posts=posts)

timesheet/users/routes.py
import sys
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import login_user, current_user, logout_user, login_required
from timesheet import db, bcrypt
from datetime import datetime, date
from timesheet.models import User, Daily
from timesheet.users.forms import LoginForm, RegistrationForm, AccountForm

users = Blueprint('users', __name__)
todays_datetime = datetime(datetime.today().year, datetime.today().month, datetime.today().day)

@users.route('/login', methods=['GET','POST'])
def login():

    def time_in(): #refactor

        check_user = Daily.query.filter_by(user_id=current_user.username).filter_by(date_today=todays_datetime).first()    #check if name and date today exists day.date_today.strftime("%Y/%m/%d
        if check_user is None:
            day = Daily(time_in=datetime.now().strftime("%H:%M"), user_id=current_user.username) #remove seconds
            db.session.add(day)
            db.session.commit()
 
            return day

        return None

    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            time_in()

            return redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='login', form=form)
    

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route('/time_out')
@login_required
def time_out():

    user = Daily.query.filter_by(user_id=current_user.username).filter_by(date_today=todays_datetime).first()
    user.time_out = datetime.now().strftime("%H:%M")
    db.session.commit()
    flash('You have timed out!', 'success')
    daily = Daily.query.order_by(Daily.time_in.desc())


    return render_template('posts.html', title='Timed Out',
                           daily=daily)

@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(name=form.fname.data + ' ' + form.lname.data, username=form.username.data, email=form.email.data, 
                    position=form.position.data, password=hashed_password)
        
        #TODO validate if user already exists
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route('/profile', methods=['GET','POST'])
@login_required
def profile():
    form = AccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    return render_template('profile.html', title='Account', form=form)

timesheet/templates/homepage.html
{% extends "layout.html" %}

{% block content %}
    <div class="table table-responsive">
        <table class="table table-hover" style="width:100%">
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Date</th>
                <th>Time In</th>
                <th>Time Out</th>
            </tr>
        {% for day in daily %}
            <tr>
                <td>{{ day.employee.name }}</td>
                <td>{{ day.employee.position }}</td>
                <td>{{ day.date_today.strftime("%Y/%m/%d") }}</td>
                <td>{{ day.time_in }}</td>
                {% if day.time_out %}
                    <td>{{ day.time_out }}</td>
                {% else %}
                    <!-- <td><button type="button" class="btn btn-primary">Timeout</button></td> -->
                    <td><a href="{{ url_for('users.time_out') }}" role='button' class="btn btn-primary">Timeout</a></td>
                {% endif %}
                
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock content %}

timesheet/templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
  <!-- Custom styles for this template -->

    
  {% if title %}
  <title>{{ title }}</title>
  {% else %}
  <title>Timesheet</title>
  {% endif %}

</head>

<body>
  <header class="site-header">
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Time Thingy</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="{{ url_for('main.home') }}">Home</a>
            </li>

            <li class="nav-item">
              {% if current_user.is_authenticated %}   
                <a class="nav-link js-scroll-trigger" href="{{ url_for('users.profile') }}"">Profile</a> 
              {% else %}
                <a class="nav-link js-scroll-trigger" href="{{ url_for('users.register') }}"">Register</a>
              {% endif %}
            </li>

            <li class="nav-item">
              {% if current_user.is_authenticated %}   
                <a class="nav-link js-scroll-trigger" href="{{ url_for('users.logout') }}"">Logout</a>
              {% else %}
                <a class="nav-link js-scroll-trigger" href="{{ url_for('users.login') }}"">Login</a>
              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <main role="main">
    <div class="row">
      <div class="col-md-12">
        {% with messages = get_flashed_messages(with_categories=true) %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
        
    
        {%block content%}{% endblock %}
      </div>
    </div>
  </main>

     <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


</body>

</html>

timesheet/templates/login.html
{%extends "layout.html"%}
<!------ Include the above in your HEAD tag ----------> 
{% block content %}
    <!-- <div class="wrapper fadeInDown"> -->
    <div class="container col-md-3 content-section">

            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.username.label(class="from-control-label") }}
                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="from-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password }}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-outline-info") }}
                </div>
            </form>                   
            <!-- Remind Passowrd -->
            <div id="formFooter">
                <a class="underlineHover" href="#">Forgot Password?</a>
            </div>
        </div>
    </div>
{% endblock content %}

timesheet/templates/posts.html
{% extends "layout.html" %}

{% block content %}
    <div class="table table-responsive" style="padding-top: 50px">
        <table class="table table-hover" style="width:100%">
            <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Date</th>
                <th>Time In</th>
                <th>Time Out</th>
            </tr>
        {% for day in daily %}
            <tr>
                <td>{{ day.employee.name }}</td>
                <td>{{ day.employee.position }}</td>
                <td>{{ day.date_today.strftime("%Y/%m/%d") }}</td>
                <td>{{ day.time_in }}</td>
                {% if day.time_out %}
                    <td>{{ day.time_out }}</td>
                {% else %}
                    <!-- <td><button type="button" class="btn btn-primary">Timeout</button></td> -->
                    <td><a href="{{ url_for('users.time_out') }}" role='button' class="btn btn-primary">Timeout</a></td>
                {% endif %}
                
            </tr>
        {% endfor %}
        </table>
    </div>
{% endblock content %}

timesheet/templates/profile.html
{% extends 'layout.html' %}
{% block content %}

<div class="content-section container col-md-8">
    <div class="media">
        <img class="rounded-circle account-img">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
        </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Account Info</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}

                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="form-control form-control-lg") }}
                {% endif %}
            </div>
           
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>


{% endblock content %}

timesheet/templates/register.html
{% extends 'layout.html' %}
{% block content %}
    <div class="container col-md-5 content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group-lg">
                    {{ form.fname.label(class="form-control-label") }}

                    {% if form.fname.errors %}
                        {{ form.fname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.fname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.fname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group-lg">
                    {{ form.lname.label(class="form-control-label") }}

                    {% if form.lname.errors %}
                        {{ form.lname(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.lname.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.lname(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group-lg">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group-lg">
                    {{ form.email.label(class="form-control-label") }}

                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group-lg">
                    {{ form.position.label(class="form-control-label") }}

                    {% if form.position.errors %}
                        {{ form.position(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.position.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.position(class="form-control form-control-lg") }}
                    {% endif %}
                </div>

                <div class="form-group-lg">
                    {{ form.password.label(class="form-control-label") }}

                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                
                <div class="form-group-lg">
                    {{ form.confirm_password.label(class="form-control-label") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group-lg">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}